<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Authors>Mirek</Authors>
    <PackageProjectUrl>https://github.com/mirosuav/Rebus.InProcCors</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mirosuav/Rebus.InProcCors</RepositoryUrl>
    <VersionPrefix>0.1.0</VersionPrefix>
  </PropertyGroup>
</Project>
